# Generated by Django 3.0.3 on 2020-06-17 14:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogAdmin', '0005_auto_20200617_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', editable=False)),
                ('cover_img', models.ImageField(upload_to='blog/article-category-cover')),
                ('summary', models.TextField(default='default summary')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PGSM', max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='blog/favicon')),
            ],
            options={
                'verbose_name': 'Blog information',
                'verbose_name_plural': 'Blog information',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, default='blogAdmin/default-cover-article/default-cover.jpg', upload_to='blog/article-cover')),
                ('summary', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tag', models.CharField(blank=True, max_length=250)),
                ('hide', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogAdmin.Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ArticleCategory')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
