# Generated by Django 2.2.7 on 2019-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='summary',
            field=models.TextField(default='default summary'),
        ),
    ]
