# Generated by Django 2.2.7 on 2019-11-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcategory_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, unique=True)),
                ('summary', models.TextField()),
                ('cover', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory')),
            ],
        ),
    ]
