# Generated by Django 3.0.3 on 2020-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200618_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='number_of_article',
            field=models.IntegerField(blank=True, default=9, help_text='number of article will be showed in home page', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
