# Generated by Django 3.0.3 on 2020-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200618_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='number_of_article_category',
            field=models.IntegerField(blank=True, default=9, help_text='number of article will be showed in category page', null=True),
        ),
    ]
