# Generated by Django 3.0 on 2019-12-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='ArticleCategory',
        ),
    ]
