# Generated by Django 2.2.7 on 2019-12-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191215_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
