# Generated by Django 2.2 on 2019-12-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191222_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
