# Generated by Django 2.2 on 2019-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='article_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
