# Generated by Django 2.2.7 on 2019-12-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191223_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='article_count',
        ),
    ]
