# Generated by Django 2.2.7 on 2019-12-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_bloginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='name',
            field=models.CharField(default='PGSM', max_length=50, unique=True),
        ),
    ]
