# Generated by Django 2.2.7 on 2020-02-10 03:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191225_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'verbose_name': 'Blog information', 'verbose_name_plural': 'Blog information'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
