# Generated by Django 3.0.3 on 2020-05-05 08:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, default='', max_length=50)),
                ('bio', ckeditor.fields.RichTextField()),
                ('fb_link', models.CharField(blank=True, max_length=250, verbose_name='Facebook')),
                ('address', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='user/profile-pic', verbose_name='Avatar')),
                ('cover_pic', models.ImageField(blank=True, upload_to='user/cover-pic', verbose_name='Cover')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
