# Generated by Django 3.0.3 on 2020-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0002_auto_20200505_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nick_name',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
