# Generated by Django 3.0.3 on 2020-06-18 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogAdmin', '0005_auto_20200617_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorProfile',
        ),
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'verbose_name': 'AuthorProfile', 'verbose_name_plural': 'AuthorProfile'},
        ),
    ]
